# Generated by Django 5.0.4 on 2024-05-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('result', models.TextField(null=True)),
                ('report', models.CharField(choices=[('처리전', '처리전'), ('처리중', '처리중'), ('처리완료', '처리완료')], default='처리전', max_length=10)),
                ('information', models.TextField(blank=True)),
                ('time', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
