# Generated by Django 5.0.4 on 2024-05-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='address',
        ),
    ]
