# Generated by Django 5.0.4 on 2024-05-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot', '0002_rename_title_post_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
