# Generated by Django 5.0.4 on 2024-05-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot', '0003_mymodel_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
