# Generated by Django 5.0.4 on 2024-05-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot', '0004_post_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
