# Generated by Django 5.0.4 on 2024-05-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot', '0005_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='%Y/%m/%d'),
        ),
    ]
